## Imports and Config

In [12]:
import pandas as pd
import numpy as np
import random
import os
from tqdm import tqdm
np.random.seed(42)
random.seed(42)

DATA_PATH = "/app/data/raw"
os.makedirs(DATA_PATH, exist_ok=True)

## Build Route Dimension

In [2]:
cities = ["Bangalore", "Chennai", "Hyderabad", "Mumbai", "Pune", "Delhi"]

In [4]:
distance_map = {
    ("Bangalore", "Chennai"): 350,
    ("Bangalore", "Hyderabad"): 570,
    ("Bangalore", "Mumbai"): 980,
    ("Bangalore", "Pune"): 840,
    ("Bangalore", "Delhi"): 2150,

    ("Chennai", "Hyderabad"): 630,
    ("Chennai", "Mumbai"): 1330,
    ("Chennai", "Pune"): 1150,
    ("Chennai", "Delhi"): 2200,

    ("Hyderabad", "Mumbai"): 710,
    ("Hyderabad", "Pune"): 560,
    ("Hyderabad", "Delhi"): 1550,

    ("Mumbai", "Pune"): 150,
    ("Mumbai", "Delhi"): 1400,

    ("Pune", "Delhi"): 1450,
}

In [5]:
def get_distance(src, dest):
    if (src, dest) in distance_map:
        base = distance_map[(src, dest)]
    elif (dest, src) in distance_map:
        base = distance_map[(dest, src)]
    else:
        base = random.randint(300, 1500)  # fallback (rare)

    # add slight randomness (real-world variation)
    return int(base * random.uniform(0.9, 1.1))

In [6]:
routes = []
route_id = 1

for src in cities:
    for dest in cities:
        if src != dest:
            routes.append({
                "route_id": route_id,
                "source_city": src,
                "destination_city": dest,
                "distance_km": get_distance(src, dest),
                "avg_speed_kmph": random.randint(40, 80),
                "traffic_factor": round(random.uniform(0.8, 1.5), 2)
            })
            route_id += 1

routes_df = pd.DataFrame(routes)
routes_df.head()

,route_id,source_city,destination_city,distance_km,avg_speed_kmph,traffic_factor
0,1,Bangalore,Chennai,342,69,0.90
1,2,Bangalore,Hyderabad,528,75,1.18
2,3,Bangalore,Mumbai,1028,67,1.43
3,4,Bangalore,Pune,823,54,1.50
4,5,Bangalore,Delhi,1994,71,0.86

## Trucks Dimension

In [7]:
truck_models = [
    {"brand": "BharatBenz", "model": "1217R", "capacity_range": (10, 16), "efficiency_range": (4, 6)},
    {"brand": "Tata", "model": "Ultra 1518", "capacity_range": (12, 18), "efficiency_range": (4, 7)},
    {"brand": "Ashok Leyland", "model": "Ecomet", "capacity_range": (10, 16), "efficiency_range": (4, 6)},
    {"brand": "Volvo", "model": "FM 420", "capacity_range": (20, 30), "efficiency_range": (3, 5)},
    {"brand": "MAN", "model": "CLA 31.300", "capacity_range": (18, 28), "efficiency_range": (3, 5)},
    {"brand": "Daimler", "model": "Actros", "capacity_range": (20, 30), "efficiency_range": (3, 5)},
]

In [9]:
n_trucks = 1000

truck_records = []

for i in range(1, n_trucks + 1):
    model_info = random.choice(truck_models)
    
    capacity = random.randint(*model_info["capacity_range"])
    efficiency = round(random.uniform(*model_info["efficiency_range"]), 2)

    truck_records.append({
        "truck_id": i,
        "brand": model_info["brand"],
        "model": model_info["model"],
        "capacity_tons": capacity,
        "fuel_efficiency_kmpl": efficiency,
        "status": random.choices(["available", "unavailable"], weights=[0.9, 0.1])[0]
    })

trucks_df = pd.DataFrame(truck_records)
trucks_df["cost_per_km"] = round(1 / trucks_df["fuel_efficiency_kmpl"], 3)
trucks_df.head()

,truck_id,brand,model,capacity_tons,fuel_efficiency_kmpl,status,cost_per_km
0,1,Volvo,FM 420,27,3.09,available,0.324
1,2,Ashok Leyland,Ecomet,10,5.41,available,0.185
2,3,Daimler,Actros,29,4.45,available,0.225
3,4,Daimler,Actros,25,4.04,available,0.248
4,5,MAN,CLA 31.300,19,3.87,available,0.258

## Drivers Dimension

In [10]:
n_drivers = 1000

drivers_df = pd.DataFrame({
    "driver_id": range(1, n_drivers + 1),
    "max_hours_per_day": np.random.randint(8, 12, n_drivers),
    "experience_level": np.random.choice(["junior", "mid", "senior"], n_drivers),
    "fatigue_factor": np.round(np.random.uniform(0.8, 1.2, n_drivers), 2)
})

drivers_df.head()

   driver_id  max_hours_per_day experience_level  fatigue_factor
0          1                 10              mid            1.16
1          2                 11           senior            1.20
2          3                  8           junior            0.82
3          4                 10           junior            1.15
4          5                 10           junior            1.01

## Trips Fact

In [11]:
n_trips = 100000

sampled_routes = routes_df.sample(n=n_trips, replace=True).reset_index(drop=True)

trips_df = pd.DataFrame({
    "trip_id": range(1, n_trips + 1),
    "route_id": sampled_routes["route_id"],
    "source_city": sampled_routes["source_city"],
    "destination_city": sampled_routes["destination_city"],
    "distance_km": sampled_routes["distance_km"],
    "load_tons": np.random.randint(1, 25, n_trips),
    "delivery_deadline_hours": np.random.randint(5, 48, n_trips)
})

trips_df.head()

,trip_id,route_id,source_city,destination_city,distance_km,load_tons,delivery_deadline_hours
0,1,20,Mumbai,Delhi,1506,2,31
1,2,2,Bangalore,Hyderabad,528,19,21
2,3,26,Delhi,Bangalore,2116,24,16
3,4,30,Delhi,Pune,1323,16,16
4,5,30,Delhi,Pune,1323,5,39

In [12]:
routes_df.to_parquet(f"{DATA_PATH}/routes.parquet", index=False)
trucks_df.to_parquet(f"{DATA_PATH}/trucks.parquet", index=False)
drivers_df.to_parquet(f"{DATA_PATH}/drivers.parquet", index=False)
trips_df.to_parquet(f"{DATA_PATH}/trips.parquet", index=False)

In [13]:
print("Routes:", routes_df.shape)
print("Trucks:", trucks_df.shape)
print("Drivers:", drivers_df.shape)
print("Trips:", trips_df.shape)

Routes: (30, 6)
Trucks: (1000, 7)
Drivers: (1000, 4)
Trips: (100000, 7)

### Add Time Constraint

In [3]:
routes_df = pd.read_parquet(f"{DATA_PATH}/routes.parquet")
trucks_df = pd.read_parquet(f"{DATA_PATH}/trucks.parquet")
drivers_df = pd.read_parquet(f"{DATA_PATH}/drivers.parquet")
trips_df = pd.read_parquet(f"{DATA_PATH}/trips.parquet")

In [4]:
# Define date range (simulate 7 days)
date_range = pd.date_range(start="2026-01-01", periods=7)

trips_df["trip_date"] = np.random.choice(date_range, size=len(trips_df))
trips_df["planned_start_hour"] = np.random.randint(0, 24, len(trips_df))

In [5]:
# Merge route info
trips_df = trips_df.merge(
    routes_df[["route_id", "avg_speed_kmph", "traffic_factor"]],
    on="route_id",
    how="left"
)

# Calculate duration
trips_df["estimated_duration_hours"] = (
    trips_df["distance_km"] /
    (trips_df["avg_speed_kmph"] / trips_df["traffic_factor"])
).round(2)
trips_df = trips_df.drop(columns=["avg_speed_kmph", "traffic_factor"])

In [6]:
buffer_factor = np.random.uniform(1.1, 1.5, len(trips_df))

trips_df["delivery_deadline_hours"] = (
    trips_df["estimated_duration_hours"] * buffer_factor
).round(2)

In [7]:
# 10% trips will have tight/unrealistic deadlines
mask = np.random.rand(len(trips_df)) < 0.1

trips_df.loc[mask, "delivery_deadline_hours"] = (
    trips_df.loc[mask, "estimated_duration_hours"] *
    np.random.uniform(0.7, 0.95, mask.sum())
).round(2)

In [8]:
trips_df["is_deadline_feasible"] = (
    trips_df["estimated_duration_hours"] <= trips_df["delivery_deadline_hours"]
)
trips_df["trip_end_hour"] = (trips_df["planned_start_hour"] + trips_df["estimated_duration_hours"])

## Assignment System

In [9]:
available_trucks = trucks_df[trucks_df["status"] == "available"].copy()
available_trucks = available_trucks.sort_values("fuel_efficiency_kmpl",ascending = False)
driver_schedule = {
    driver_id: {} for driver_id in drivers_df["driver_id"]
}

In [13]:
assignments = []
assignment_id = 1

trips_df_sample = trips_df.sample(10000)

for date in tqdm(trips_df_sample["trip_date"].sort_values().unique(), desc="Days"):
    
    daily_trips = trips_df_sample[
        trips_df_sample["trip_date"] == date
    ]
    
    print(f"\nProcessing date: {date}, Trips: {len(daily_trips)}")
    for _, trip in tqdm(daily_trips.iterrows(), total=len(daily_trips), leave=False):
        
        eligible_drivers = drivers_df.sample(min(50, len(drivers_df))) 
        trip_start = trip["planned_start_hour"]
        trip_end = trip["trip_end_hour"]
        trip_date = trip["trip_date"]
        load = trip["load_tons"]
        
        # 1. Find valid trucks
        valid_trucks = available_trucks[
            available_trucks["capacity_tons"] >= load
        ]
        
        if valid_trucks.empty:
            continue
        
        # Pick cheapest truck (fuel efficiency proxy)
        truck = valid_trucks.iloc[0]
        
        # 2. Find valid driver
        assigned_driver = None
        
        for _, driver in eligible_drivers.iterrows():
            driver_id = driver["driver_id"]
            max_hours = driver["max_hours_per_day"]
            
            # Get existing schedule
            day_schedule = driver_schedule[driver_id].get(trip_date, [])
            
            # Check overlap
            overlap = any(
                not (trip_end <= s or trip_start >= e)
                for s, e in day_schedule
            )
            
            total_hours = sum(e - s for s, e in day_schedule)
            
            if not overlap and (total_hours + (trip_end - trip_start)) <= max_hours:
                assigned_driver = driver_id
                
                # Update schedule
                driver_schedule[driver_id].setdefault(trip_date, []).append(
                    (trip_start, trip_end)
                )
                break
        
        if assigned_driver is None:
            continue
        
        # 3. Create assignment
        assignments.append({
            "assignment_id": assignment_id,
            "trip_id": trip["trip_id"],
            "truck_id": truck["truck_id"],
            "driver_id": assigned_driver,
            "route_id": trip["route_id"],
            "trip_date": trip_date,
            "start_hour": trip_start,
            "end_hour": trip_end,
            "estimated_duration_hours": trip["estimated_duration_hours"]
        })
        
        assignment_id += 1

Days:   0%|          | 0/7 [00:00<?, ?it/s]

Processing date: 2026-01-01 00:00:00, Trips: 1419

  0%|          | 0/1419 [00:00<?, ?it/s]

  2%|▏         | 33/1419 [00:00<00:04, 325.99it/s]

  5%|▍         | 66/1419 [00:00<00:04, 316.78it/s]

  9%|▉         | 125/1419 [00:00<00:02, 438.13it/s]

 12%|█▏        | 170/1419 [00:00<00:03, 383.69it/s]

 15%|█▍        | 210/1419 [00:00<00:03, 363.10it/s]

 18%|█▊        | 253/1419 [00:00<00:03, 381.46it/s]

 21%|██        | 292/1419 [00:00<00:03, 334.18it/s]

 24%|██▎       | 334/1419 [00:00<00:03, 355.13it/s]

 26%|██▌       | 371/1419 [00:01<00:02, 352.02it/s]

 29%|██▉       | 413/1419 [00:01<00:02, 370.11it/s]

 32%|███▏      | 458/1419 [00:01<00:02, 387.21it/s]

 35%|███▌      | 498/1419 [00:01<00:02, 335.75it/s]

 39%|███▊      | 547/1419 [00:01<00:02, 371.18it/s]

 41%|████▏     | 586/1419 [00:01<00:02, 285.38it/s]

 44%|████▍     | 624/1419 [00:01<00:02, 304.17it/s]

 48%|████▊     | 679/1419 [00:01<00:02, 363.32it/s]

 51%|█████     | 719/1419 [00:02<00:01, 366.26it/s]

 54%|█████▍    | 767/1419 [00:02<00:01, 395.49it/s]

 57%|█████▋    | 815/1419 [00:02<00:01, 416.45it/s]

 61%|██████    | 859/1419 [00:02<00:01, 405.03it/s]

 64%|██████▍   | 914/1419 [00:02<00:01, 443.78it/s]

 68%|██████▊   | 972/1419 [00:02<00:00, 480.07it/s]

 73%|███████▎  | 1029/1419 [00:02<00:00, 504.45it/s]

 76%|███████▌  | 1081/1419 [00:02<00:00, 504.15it/s]

 80%|███████▉  | 1132/1419 [00:02<00:00, 453.44it/s]

 83%|████████▎ | 1179/1419 [00:03<00:00, 380.80it/s]

 87%|████████▋ | 1229/1419 [00:03<00:00, 408.95it/s]

 90%|█████████ | 1279/1419 [00:03<00:00, 429.42it/s]

 93%|█████████▎| 1324/1419 [00:03<00:00, 414.21it/s]

 97%|█████████▋| 1375/1419 [00:03<00:00, 439.30it/s]


Days:  14%|█▍        | 1/7 [00:03<00:21,  3.61s/it]

Processing date: 2026-01-02 00:00:00, Trips: 1426

  0%|          | 0/1426 [00:00<?, ?it/s]

  5%|▍         | 66/1426 [00:00<00:02, 648.08it/s]

  9%|▉         | 131/1426 [00:00<00:02, 585.12it/s]

 13%|█▎        | 190/1426 [00:00<00:02, 564.41it/s]

 17%|█▋        | 247/1426 [00:00<00:02, 509.61it/s]

 21%|██        | 299/1426 [00:00<00:02, 503.05it/s]

 25%|██▍       | 355/1426 [00:00<00:02, 518.33it/s]

 29%|██▉       | 415/1426 [00:00<00:01, 538.98it/s]

 34%|███▎      | 478/1426 [00:00<00:01, 564.35it/s]

 38%|███▊      | 539/1426 [00:00<00:01, 576.60it/s]

 42%|████▏     | 597/1426 [00:01<00:01, 567.33it/s]

 46%|████▌     | 654/1426 [00:01<00:01, 495.10it/s]

 50%|████▉     | 706/1426 [00:01<00:01, 483.40it/s]

 53%|█████▎    | 756/1426 [00:01<00:01, 456.64it/s]

 56%|█████▋    | 803/1426 [00:01<00:01, 432.55it/s]

 59%|█████▉    | 847/1426 [00:01<00:01, 361.58it/s]

 62%|██████▏   | 886/1426 [00:01<00:01, 306.44it/s]

 66%|██████▌   | 936/1426 [00:02<00:01, 349.01it/s]

 69%|██████▉   | 990/1426 [00:02<00:01, 394.33it/s]

 73%|███████▎  | 1037/1426 [00:02<00:00, 411.93it/s]

 76%|███████▌  | 1087/1426 [00:02<00:00, 434.52it/s]

 80%|████████  | 1143/1426 [00:02<00:00, 468.22it/s]

 85%|████████▍ | 1205/1426 [00:02<00:00, 510.37it/s]

 88%|████████▊ | 1258/1426 [00:02<00:00, 501.17it/s]

 92%|█████████▏| 1310/1426 [00:02<00:00, 489.65it/s]

 96%|█████████▌| 1368/1426 [00:02<00:00, 515.04it/s]

100%|█████████▉| 1421/1426 [00:03<00:00, 467.47it/s]


Days:  29%|██▊       | 2/7 [00:06<00:16,  3.28s/it]

Processing date: 2026-01-03 00:00:00, Trips: 1409

  0%|          | 0/1409 [00:00<?, ?it/s]

  2%|▏         | 24/1409 [00:00<00:06, 228.83it/s]

  4%|▍         | 60/1409 [00:00<00:04, 302.77it/s]

  9%|▊         | 121/1409 [00:00<00:02, 440.11it/s]

 13%|█▎        | 178/1409 [00:00<00:02, 489.30it/s]

 16%|█▋        | 229/1409 [00:00<00:02, 495.88it/s]

 20%|██        | 282/1409 [00:00<00:02, 505.23it/s]

 24%|██▎       | 333/1409 [00:00<00:02, 493.32it/s]

 27%|██▋       | 387/1409 [00:00<00:02, 505.74it/s]

 31%|███       | 440/1409 [00:00<00:01, 509.61it/s]

 35%|███▍      | 492/1409 [00:01<00:01, 463.72it/s]

 38%|███▊      | 540/1409 [00:01<00:01, 438.37it/s]

 42%|████▏     | 585/1409 [00:01<00:02, 392.97it/s]

 45%|████▍     | 629/1409 [00:01<00:01, 403.64it/s]

 48%|████▊     | 677/1409 [00:01<00:01, 422.76it/s]

 52%|█████▏    | 731/1409 [00:01<00:01, 449.37it/s]

 55%|█████▌    | 777/1409 [00:01<00:01, 439.41it/s]

 58%|█████▊    | 822/1409 [00:01<00:01, 413.96it/s]

 61%|██████▏   | 864/1409 [00:01<00:01, 395.85it/s]

 66%|██████▌   | 932/1409 [00:02<00:01, 472.07it/s]

 70%|██████▉   | 981/1409 [00:02<00:00, 472.22it/s]

 73%|███████▎  | 1032/1409 [00:02<00:00, 482.48it/s]

 77%|███████▋  | 1085/1409 [00:02<00:00, 490.50it/s]

 81%|████████  | 1135/1409 [00:02<00:00, 352.79it/s]

 84%|████████▍ | 1187/1409 [00:02<00:00, 389.49it/s]

 88%|████████▊ | 1237/1409 [00:02<00:00, 413.38it/s]

 91%|█████████ | 1283/1409 [00:02<00:00, 409.72it/s]

 94%|█████████▍| 1327/1409 [00:03<00:00, 409.12it/s]

 97%|█████████▋| 1370/1409 [00:03<00:00, 401.74it/s]


Days:  43%|████▎     | 3/7 [00:09<00:13,  3.27s/it]

Processing date: 2026-01-04 00:00:00, Trips: 1472

  0%|          | 0/1472 [00:00<?, ?it/s]

  4%|▍         | 56/1472 [00:00<00:02, 559.23it/s]

  8%|▊         | 112/1472 [00:00<00:02, 484.89it/s]

 11%|█         | 162/1472 [00:00<00:02, 477.16it/s]

 14%|█▍        | 211/1472 [00:00<00:03, 329.08it/s]

 18%|█▊        | 258/1472 [00:00<00:03, 365.41it/s]

 21%|██▏       | 313/1472 [00:00<00:02, 414.72it/s]

 24%|██▍       | 360/1472 [00:00<00:02, 428.68it/s]

 28%|██▊       | 414/1472 [00:00<00:02, 459.87it/s]

 32%|███▏      | 474/1472 [00:01<00:02, 498.28it/s]

 36%|███▌      | 531/1472 [00:01<00:01, 518.65it/s]

 40%|████      | 590/1472 [00:01<00:01, 539.15it/s]

 44%|████▍     | 645/1472 [00:01<00:01, 538.25it/s]

 48%|████▊     | 706/1472 [00:01<00:01, 558.22it/s]

 52%|█████▏    | 763/1472 [00:01<00:01, 538.81it/s]

 56%|█████▌    | 818/1472 [00:01<00:01, 458.05it/s]

 59%|█████▉    | 867/1472 [00:01<00:01, 433.86it/s]

 63%|██████▎   | 926/1472 [00:01<00:01, 471.88it/s]

 66%|██████▋   | 978/1472 [00:02<00:01, 481.54it/s]

 70%|██████▉   | 1028/1472 [00:02<00:00, 485.98it/s]

 73%|███████▎  | 1078/1472 [00:02<00:00, 486.51it/s]

 77%|███████▋  | 1137/1472 [00:02<00:00, 514.19it/s]

 81%|████████  | 1190/1472 [00:02<00:00, 498.30it/s]

 84%|████████▍ | 1241/1472 [00:02<00:00, 495.04it/s]

 88%|████████▊ | 1291/1472 [00:02<00:00, 480.00it/s]

 91%|█████████ | 1340/1472 [00:02<00:00, 456.74it/s]

 94%|█████████▍| 1387/1472 [00:02<00:00, 413.27it/s]

 98%|█████████▊| 1436/1472 [00:03<00:00, 431.25it/s]


Days:  57%|█████▋    | 4/7 [00:13<00:09,  3.23s/it]

Processing date: 2026-01-05 00:00:00, Trips: 1383

  0%|          | 0/1383 [00:00<?, ?it/s]

  4%|▍         | 55/1383 [00:00<00:02, 549.40it/s]

  8%|▊         | 114/1383 [00:00<00:02, 566.78it/s]

 12%|█▏        | 171/1383 [00:00<00:02, 516.09it/s]

 16%|█▌        | 224/1383 [00:00<00:02, 511.55it/s]

 20%|█▉        | 276/1383 [00:00<00:02, 498.96it/s]

 24%|██▎       | 328/1383 [00:00<00:02, 503.74it/s]

 28%|██▊       | 384/1383 [00:00<00:01, 519.48it/s]

 32%|███▏      | 437/1383 [00:00<00:01, 498.19it/s]

 35%|███▌      | 488/1383 [00:00<00:01, 450.55it/s]

 39%|███▊      | 534/1383 [00:01<00:01, 432.71it/s]

 42%|████▏     | 587/1383 [00:01<00:01, 456.54it/s]

 47%|████▋     | 645/1383 [00:01<00:01, 489.49it/s]

 50%|█████     | 695/1383 [00:01<00:01, 481.20it/s]

 54%|█████▍    | 749/1383 [00:01<00:01, 495.17it/s]

 58%|█████▊    | 808/1383 [00:01<00:01, 520.28it/s]

 62%|██████▏   | 861/1383 [00:01<00:01, 515.01it/s]

 67%|██████▋   | 920/1383 [00:01<00:00, 536.32it/s]

 70%|███████   | 974/1383 [00:01<00:00, 500.74it/s]

 74%|███████▍  | 1025/1383 [00:02<00:00, 472.44it/s]

 78%|███████▊  | 1073/1383 [00:02<00:00, 373.40it/s]

 81%|████████  | 1123/1383 [00:02<00:00, 402.94it/s]

 85%|████████▌ | 1176/1383 [00:02<00:00, 434.83it/s]

 89%|████████▊ | 1226/1383 [00:02<00:00, 450.11it/s]

 92%|█████████▏| 1275/1383 [00:02<00:00, 458.71it/s]

 96%|█████████▌| 1323/1383 [00:02<00:00, 406.52it/s]

 99%|█████████▉| 1366/1383 [00:02<00:00, 396.74it/s]


Days:  71%|███████▏  | 5/7 [00:16<00:06,  3.15s/it]

Processing date: 2026-01-06 00:00:00, Trips: 1462

  0%|          | 0/1462 [00:00<?, ?it/s]

  3%|▎         | 39/1462 [00:00<00:03, 366.19it/s]

  5%|▌         | 76/1462 [00:00<00:04, 326.33it/s]

  7%|▋         | 109/1462 [00:00<00:05, 260.88it/s]

 10%|█         | 147/1462 [00:00<00:04, 297.63it/s]

 13%|█▎        | 189/1462 [00:00<00:03, 335.25it/s]

 15%|█▌        | 224/1462 [00:00<00:03, 327.73it/s]

 18%|█▊        | 265/1462 [00:00<00:03, 351.78it/s]

 22%|██▏       | 319/1462 [00:00<00:02, 406.73it/s]

 25%|██▍       | 365/1462 [00:01<00:02, 418.36it/s]

 28%|██▊       | 412/1462 [00:01<00:02, 431.99it/s]

 31%|███▏      | 457/1462 [00:01<00:02, 436.39it/s]

 34%|███▍      | 501/1462 [00:01<00:02, 427.81it/s]

 37%|███▋      | 545/1462 [00:01<00:02, 429.73it/s]

 40%|████      | 589/1462 [00:01<00:02, 356.96it/s]

 43%|████▎     | 627/1462 [00:01<00:02, 352.58it/s]

 46%|████▋     | 678/1462 [00:01<00:01, 392.29it/s]

 50%|████▉     | 725/1462 [00:01<00:01, 413.09it/s]

 53%|█████▎    | 768/1462 [00:02<00:01, 401.69it/s]

 55%|█████▌    | 810/1462 [00:02<00:01, 376.87it/s]

 59%|█████▊    | 858/1462 [00:02<00:01, 404.54it/s]

 63%|██████▎   | 915/1462 [00:02<00:01, 448.68it/s]

 66%|██████▌   | 966/1462 [00:02<00:01, 465.08it/s]

 70%|██████▉   | 1017/1462 [00:02<00:00, 477.20it/s]

 73%|███████▎  | 1066/1462 [00:02<00:00, 460.00it/s]

 76%|███████▌  | 1113/1462 [00:02<00:00, 350.94it/s]

 79%|███████▉  | 1154/1462 [00:02<00:00, 364.69it/s]

 83%|████████▎ | 1208/1462 [00:03<00:00, 408.60it/s]

 86%|████████▌ | 1252/1462 [00:03<00:00, 408.70it/s]

 89%|████████▉ | 1303/1462 [00:03<00:00, 435.55it/s]

 93%|█████████▎| 1353/1462 [00:03<00:00, 451.56it/s]

 96%|█████████▌| 1400/1462 [00:03<00:00, 387.51it/s]

 99%|█████████▊| 1442/1462 [00:03<00:00, 381.74it/s]


Days:  86%|████████▌ | 6/7 [00:19<00:03,  3.35s/it]

Processing date: 2026-01-07 00:00:00, Trips: 1429

  0%|          | 0/1429 [00:00<?, ?it/s]

  4%|▎         | 51/1429 [00:00<00:02, 508.31it/s]

  7%|▋         | 102/1429 [00:00<00:02, 475.87it/s]

 10%|█         | 150/1429 [00:00<00:03, 337.95it/s]

 13%|█▎        | 188/1429 [00:00<00:03, 350.48it/s]

 16%|█▌        | 226/1429 [00:00<00:03, 349.18it/s]

 20%|█▉        | 282/1429 [00:00<00:02, 411.81it/s]

 23%|██▎       | 332/1429 [00:00<00:02, 434.36it/s]

 27%|██▋       | 384/1429 [00:00<00:02, 458.22it/s]

 31%|███       | 440/1429 [00:01<00:02, 488.06it/s]

 35%|███▍      | 499/1429 [00:01<00:01, 517.71it/s]

 39%|███▉      | 555/1429 [00:01<00:01, 528.29it/s]

 43%|████▎     | 611/1429 [00:01<00:01, 537.37it/s]

 47%|████▋     | 666/1429 [00:01<00:01, 509.68it/s]

 50%|█████     | 718/1429 [00:01<00:02, 349.22it/s]

 53%|█████▎    | 764/1429 [00:01<00:01, 373.10it/s]

 57%|█████▋    | 816/1429 [00:01<00:01, 407.08it/s]

 60%|██████    | 862/1429 [00:02<00:01, 390.35it/s]

 64%|██████▍   | 919/1429 [00:02<00:01, 433.20it/s]

 68%|██████▊   | 976/1429 [00:02<00:00, 467.33it/s]

 72%|███████▏  | 1035/1429 [00:02<00:00, 498.64it/s]

 76%|███████▌  | 1088/1429 [00:02<00:00, 506.48it/s]

 80%|███████▉  | 1141/1429 [00:02<00:00, 510.80it/s]

 84%|████████▍ | 1197/1429 [00:02<00:00, 521.97it/s]

 88%|████████▊ | 1251/1429 [00:02<00:00, 330.13it/s]

 91%|█████████▏| 1306/1429 [00:03<00:00, 374.53it/s]

 96%|█████████▌| 1374/1429 [00:03<00:00, 443.25it/s]


Days: 100%|██████████| 7/7 [00:23<00:00,  3.30s/it]

## Upgrading Assignment Functions (Considering more parameters like Fuel Cost, Driver Cost, Penalty)

In [14]:
def compute_cost(truck, trip):
    """
    Compute total operational cost for assigning a truck to a trip.
    
    Inputs:
        truck -> row from trucks_df
        trip  -> row from trips_df
        
    Returns:
        total_cost (float)
    """
    
    # ---------------------------
    # CONFIG (can move to config file later)
    # ---------------------------
    FUEL_PRICE = 100      # per litre
    DRIVER_RATE = 200     # per hour
    LATE_PENALTY = 500    # per hour delay
    
    # ---------------------------
    # EXTRACT VALUES
    # ---------------------------
    distance = trip["distance_km"]
    duration = trip["estimated_duration_hours"]
    deadline = trip["delivery_deadline_hours"]
    load = trip["load_tons"]
    base_efficiency = truck["fuel_efficiency_kmpl"]
    
    # ---------------------------
    # REALISM ADJUSTMENTS
    # ---------------------------
    
    # Load impact → heavier load reduces efficiency
    load_factor = 1 + (load / truck["capacity_tons"]) * 0.2
    
    # Optional: traffic impact (if available in trip later)
    # traffic_factor = trip.get("traffic_factor", 1.0)
    
    adjusted_efficiency = base_efficiency / load_factor
    
    # Avoid divide-by-zero
    adjusted_efficiency = max(adjusted_efficiency, 0.1)
    
    # ---------------------------
    # COST COMPONENTS
    # ---------------------------
    
    # Fuel cost (distance-based)
    fuel_cost = (distance / adjusted_efficiency) * FUEL_PRICE
    
    # Driver cost (time-based)
    driver_cost = duration * DRIVER_RATE
    
    # Delay penalty
    delay = max(0, duration - deadline)
    penalty = delay * LATE_PENALTY
    
    # ---------------------------
    # TOTAL COST
    # ---------------------------
    total_cost = fuel_cost + driver_cost + penalty
    
    return round(total_cost, 2)

In [15]:
def assign_trips(trips_df, trucks_df, drivers_df, max_driver_candidates=50, max_truck_candidates=5):
    """
    Assign trucks and drivers to trips using cost-based heuristic.

    Parameters:
        trips_df (DataFrame)
        trucks_df (DataFrame)
        drivers_df (DataFrame)
        max_driver_candidates (int): number of drivers to sample per trip
        max_truck_candidates (int): number of trucks to evaluate per trip

    Returns:
        assignments_df (DataFrame)
    """
    
    from tqdm import tqdm
    
    # ---------------------------
    # PREP
    # ---------------------------
    
    assignments = []
    assignment_id = 1
    
    # Only available trucks
    available_trucks = trucks_df[trucks_df["status"] == "available"].copy()
    
    # Pre-sort trucks (better first)
    available_trucks = available_trucks.sort_values(
        "fuel_efficiency_kmpl", ascending=False
    )
    
    # Driver schedule tracker
    driver_schedule = {
        driver_id: {} for driver_id in drivers_df["driver_id"]
    }
    
    # ---------------------------
    # LOOP BY DAY (BATCH STYLE)
    # ---------------------------
    
    for date in tqdm(trips_df["trip_date"].sort_values().unique(), desc="Days"):
        
        daily_trips = trips_df[trips_df["trip_date"] == date]
        
        for _, trip in tqdm(daily_trips.iterrows(), total=len(daily_trips), leave=False):
            
            trip_start = trip["planned_start_hour"]
            trip_end = trip["trip_end_hour"]
            load = trip["load_tons"]
            
            # ---------------------------
            # FILTER VALID TRUCKS
            # ---------------------------
            valid_trucks = available_trucks[
                available_trucks["capacity_tons"] >= load
            ].head(max_truck_candidates)
            
            if valid_trucks.empty:
                continue
            
            # ---------------------------
            # SAMPLE DRIVER CANDIDATES
            # ---------------------------
            eligible_drivers = drivers_df.sample(
                min(max_driver_candidates, len(drivers_df))
            )
            
            # ---------------------------
            # FIND BEST COMBINATION
            # ---------------------------
            best_assignment = None
            best_cost = float("inf")
            
            for _, truck in valid_trucks.iterrows():
                
                for _, driver in eligible_drivers.iterrows():
                    
                    driver_id = driver["driver_id"]
                    max_hours = driver["max_hours_per_day"]
                    
                    # Get driver schedule for the day
                    day_schedule = driver_schedule[driver_id].get(date, [])
                    
                    # Overlap check
                    overlap = any(
                        not (trip_end <= s or trip_start >= e)
                        for s, e in day_schedule
                    )
                    
                    total_hours = sum(e - s for s, e in day_schedule)
                    
                    if overlap or (total_hours + (trip_end - trip_start)) > max_hours:
                        continue
                    
                    # ---------------------------
                    # COST CALCULATION
                    # ---------------------------
                    cost = compute_cost(truck, trip)
                    
                    if cost < best_cost:
                        best_cost = cost
                        best_assignment = (truck, driver_id)
            
            # ---------------------------
            # APPLY BEST ASSIGNMENT
            # ---------------------------
            if best_assignment is None:
                continue
            
            truck, assigned_driver = best_assignment
            
            # Update driver schedule
            driver_schedule[assigned_driver].setdefault(date, []).append(
                (trip_start, trip_end)
            )
            
            # Save assignment
            assignments.append({
                "assignment_id": assignment_id,
                "trip_id": trip["trip_id"],
                "truck_id": truck["truck_id"],
                "driver_id": assigned_driver,
                "route_id": trip["route_id"],
                "trip_date": date,
                "start_hour": trip_start,
                "end_hour": trip_end,
                "estimated_duration_hours": trip["estimated_duration_hours"],
                "total_cost": best_cost
            })
            
            assignment_id += 1
    
    # ---------------------------
    # OUTPUT
    # ---------------------------
    assignments_df = pd.DataFrame(assignments)
    
    return assignments_df

In [ ]:
assignments_df = assign_trips(trips_df, trucks_df, drivers_df)

Days:   0%|          | 0/7 [00:00<?, ?it/s]

  0%|          | 0/14229 [00:00<?, ?it/s]

  0%|          | 9/14229 [00:00<02:44, 86.47it/s]

  0%|          | 18/14229 [00:00<02:58, 79.80it/s]

  0%|          | 28/14229 [00:00<02:42, 87.34it/s]

  0%|          | 40/14229 [00:00<02:24, 98.42it/s]

  0%|          | 52/14229 [00:00<02:16, 103.89it/s]

  0%|          | 63/14229 [00:00<02:14, 105.03it/s]

  1%|          | 75/14229 [00:00<02:10, 108.43it/s]

  1%|          | 87/14229 [00:00<02:07, 110.57it/s]

  1%|          | 99/14229 [00:00<02:09, 108.81it/s]

  1%|          | 110/14229 [00:01<02:10, 108.21it/s]

  1%|          | 122/14229 [00:01<02:08, 109.76it/s]

  1%|          | 133/14229 [00:01<02:08, 109.34it/s]

  1%|          | 144/14229 [00:01<02:57, 79.56it/s]

  1%|          | 154/14229 [00:01<02:53, 80.90it/s]

  1%|          | 163/14229 [00:01<02:52, 81.53it/s]

  1%|          | 175/14229 [00:01<02:35, 90.62it/s]

  1%|▏         | 185/14229 [00:01<02:32, 92.15it/s]

  1%|▏         | 195/14229 [00:02<02:31, 92.57it/s]

  1%|▏         | 205/14229 [00:02<02:30, 93.15it/s]

  2%|▏         | 216/14229 [00:02<02:23, 97.65it/s]

  2%|▏         | 227/14229 [00:02<02:19, 100.65it/s]

  2%|▏         | 240/14229 [00:02<02:10, 107.50it/s]

  2%|▏         | 251/14229 [00:02<02:19, 100.30it/s]

  2%|▏         | 262/14229 [00:02<02:35, 89.66it/s]

  2%|▏         | 273/14229 [00:02<02:29, 93.21it/s]

  2%|▏         | 283/14229 [00:02<02:27, 94.30it/s]

  2%|▏         | 294/14229 [00:03<02:21, 98.21it/s]

  2%|▏         | 305/14229 [00:03<02:17, 101.02it/s]

  2%|▏         | 316/14229 [00:03<02:15, 102.62it/s]

  2%|▏         | 327/14229 [00:03<02:16, 101.66it/s]

  2%|▏         | 338/14229 [00:03<02:17, 100.99it/s]

  2%|▏         | 349/14229 [00:03<02:23, 96.62it/s]

  3%|▎         | 359/14229 [00:03<02:30, 92.07it/s]

  3%|▎         | 369/14229 [00:03<02:49, 81.57it/s]

  3%|▎         | 378/14229 [00:03<02:49, 81.88it/s]

  3%|▎         | 389/14229 [00:04<02:39, 86.75it/s]

  3%|▎         | 399/14229 [00:04<02:33, 90.22it/s]

  3%|▎         | 409/14229 [00:04<02:29, 92.66it/s]

  3%|▎         | 419/14229 [00:04<02:33, 89.83it/s]

  3%|▎         | 429/14229 [00:04<02:29, 92.50it/s]

  3%|▎         | 439/14229 [00:04<02:32, 90.20it/s]

  3%|▎         | 449/14229 [00:04<02:31, 91.10it/s]

  3%|▎         | 460/14229 [00:04<02:25, 94.73it/s]

  3%|▎         | 470/14229 [00:04<02:36, 87.92it/s]

  3%|▎         | 479/14229 [00:05<02:52, 79.57it/s]

  3%|▎         | 488/14229 [00:05<02:54, 78.83it/s]

  4%|▎         | 499/14229 [00:05<02:40, 85.60it/s]

  4%|▎         | 511/14229 [00:05<02:25, 94.04it/s]

  4%|▎         | 522/14229 [00:05<02:20, 97.70it/s]

  4%|▎         | 532/14229 [00:05<02:47, 81.99it/s]

  4%|▍         | 541/14229 [00:05<02:47, 81.53it/s]

  4%|▍         | 552/14229 [00:05<02:34, 88.24it/s]

  4%|▍         | 562/14229 [00:06<02:29, 91.22it/s]

  4%|▍         | 572/14229 [00:06<02:41, 84.36it/s]

  4%|▍         | 581/14229 [00:06<02:51, 79.72it/s]

  4%|▍         | 590/14229 [00:06<03:03, 74.47it/s]

  4%|▍         | 601/14229 [00:06<02:44, 82.83it/s]

  4%|▍         | 612/14229 [00:06<02:33, 88.91it/s]

  4%|▍         | 623/14229 [00:06<02:25, 93.21it/s]

  4%|▍         | 633/14229 [00:06<02:24, 93.92it/s]

  5%|▍         | 643/14229 [00:06<02:23, 94.39it/s]

  5%|▍         | 653/14229 [00:07<02:25, 93.57it/s]

  5%|▍         | 664/14229 [00:07<02:19, 96.97it/s]

  5%|▍         | 676/14229 [00:07<02:13, 101.27it/s]

  5%|▍         | 688/14229 [00:07<02:08, 105.45it/s]

  5%|▍         | 699/14229 [00:07<02:17, 98.10it/s]

  5%|▍         | 709/14229 [00:07<02:33, 87.84it/s]

  5%|▌         | 719/14229 [00:07<02:33, 88.28it/s]

  5%|▌         | 729/14229 [00:07<02:31, 88.90it/s]

  5%|▌         | 739/14229 [00:08<02:31, 88.89it/s]

  5%|▌         | 748/14229 [00:08<02:38, 84.92it/s]

  5%|▌         | 759/14229 [00:08<02:31, 88.82it/s]

  5%|▌         | 768/14229 [00:08<02:36, 85.90it/s]

  5%|▌         | 780/14229 [00:08<02:24, 92.95it/s]

  6%|▌         | 790/14229 [00:08<02:26, 92.00it/s]

  6%|▌         | 800/14229 [00:08<02:28, 90.55it/s]

  6%|▌         | 810/14229 [00:08<02:43, 81.96it/s]

  6%|▌         | 819/14229 [00:08<02:46, 80.68it/s]

  6%|▌         | 829/14229 [00:09<02:39, 83.91it/s]

  6%|▌         | 841/14229 [00:09<02:26, 91.66it/s]

  6%|▌         | 852/14229 [00:09<02:18, 96.31it/s]

  6%|▌         | 863/14229 [00:09<02:14, 99.24it/s]

  6%|▌         | 875/14229 [00:09<02:07, 104.67it/s]

  6%|▌         | 887/14229 [00:09<02:03, 107.86it/s]

  6%|▋         | 898/14229 [00:09<02:06, 105.27it/s]

  6%|▋         | 909/14229 [00:09<02:06, 105.51it/s]